  - name: Run Docker image
    docker_container:
      name: "{{lookup('env','ARTIFACT_ID')}}"
      image: "{{lookup('env','DOCKER_REPO_URL')}}/{{lookup('env','ARTIFACT_ID')}}:{{lookup('env','ARTIFACT_VERSION')}}"
      state: started
      pull: yes
      published_ports: "{{lookup('env','DOCKER_CONTAINER_PORT')}}"
