  - name: Log into Docker repo
    docker_login:
      registry_url: "{{lookup('env','DOCKER_REPO_URL')}}"
      username: "{{lookup('env','NEXUS_USER')}}"
      password: "{{lookup('env','NEXUS_PASSWORD')}}"
  - name: Build an image and push it to a repo
    docker_image:
      build:
        path: "{{lookup('env','DOCKERFILE_PATH')}}"
        dockerfile: application.dockerfile
      name: "{{lookup('env','DOCKER_REPO_URL')}}/{{lookup('env','ARTIFACT_ID')}}"
      tag: "{{lookup('env','ARTIFACT_VERSION')}}"
      push: yes
      source: build
      state: present
      force: yes
