  - name: Log into DockerHub
    docker_login:
      username: "{{lookup('env','NEXUS_USER')}}"
      password: "{{lookup('env','NEXUS_PASSWORD')}}"
  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: "{{lookup('env','DOCKERFILE_PATH')}}"
        #path: ../../../../
        #path: /var/lib/jenkins/workspace/Build/spring-boot-samples/spring-boot-sample-web-ui
        dockerfile: application.dockerfile
      name: "{{lookup('env','DOCKER_REPO_URL')}}/{{lookup('env','ARTIFACT_ID')}}"
      tag: "{{lookup('env','ARTIFACT_VERSION')}}"
      push: yes
      source: build
      state: present
      force: yes
