  - name: Create and push container
    docker_image:
      name: openjdk:8-jre-alpine
      source: pull
  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: ../../../../
        dockerfile: application.dockerfile
      name: "{{lookup('env','DOCKER_REPO_URL')}}:8088/{{lookup('env','ARTIFACT_ID')}}"
      tag: "{{lookup('env','ARTIFACT_VERSION')}}"
      push: yes
      source: build
      state: present
      force: yes
